[pytest]
env =
    DATABASE_URL=postgresql://fulcrum_test:fulcrum_test@db-test:5432/fulcrum_test
markers =
    postgres: mark a test as requiring a postgres database
filterwarnings =
    ignore:'crypt' is deprecated and slated for removal in Python 3.13
