---
name: "🐞 Bug Report"
description: "File a bug report to help us improve."
title: "[BUG] - "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for taking the time to fill out this bug report.

  - type: textarea
    id: description
    attributes:
      label: "Description"
      description: "A clear and concise description of what the bug is."
      placeholder: "When I do [...] an error occurs [...]"
    validations:
      required: true

  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: "Steps to Reproduce"
      description: "Please provide detailed steps to reproduce the behavior."
      placeholder: |
        1. Go to '...'
        2. Click on '....'
        3. Scroll down to '....'
        4. See error
    validations:
      required: true

  - type: textarea
    id: expected-behavior
    attributes:
      label: "Expected Behavior"
      description: "A clear and concise description of what you expected to happen."
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: "Relevant Log Output"
      description: "Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks."
      render: shell
