"""Add marketplace listing sync fields

Revision ID: 01202be541dc
Revises: 4761955010d3
Create Date: 2025-12-28 05:56:59.128141

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '01202be541dc'
down_revision: Union[str, Sequence[str], None] = '4761955010d3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('marketplace_listings', sa.Column('sync_status', sa.String(), nullable=True))
    op.add_column('marketplace_listings', sa.Column('last_sync', sa.DateTime(timezone=True), nullable=True))
    op.add_column('marketplace_listings', sa.Column('marketplace_price', sa.Float(), nullable=True))
    op.add_column('marketplace_listings', sa.Column('error_message', sa.String(), nullable=True))
    op.add_column('marketplace_listings', sa.Column('metadata_json', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('marketplace_listings', 'metadata_json')
    op.drop_column('marketplace_listings', 'error_message')
    op.drop_column('marketplace_listings', 'marketplace_price')
    op.drop_column('marketplace_listings', 'last_sync')
    op.drop_column('marketplace_listings', 'sync_status')
    # ### end Alembic commands ###
