"""Add_Barcode_URLs_to_Product

Revision ID: 028534179c86
Revises: 03bd409f2a81
Create Date: 2026-01-03 04:13:43.810660

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '028534179c86'
down_revision: Union[str, Sequence[str], None] = '03bd409f2a81'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('barcode_image_url', sa.String(), nullable=True))
    op.add_column('products', sa.Column('qrcode_image_url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'qrcode_image_url')
    op.drop_column('products', 'barcode_image_url')
    # ### end Alembic commands ###
