"""Add_AI_keys_to_StoreSettings

Revision ID: 03bd409f2a81
Revises: 1b278953a6ce
Create Date: 2026-01-03 04:11:30.422339

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '03bd409f2a81'
down_revision: Union[str, Sequence[str], None] = '1b278953a6ce'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('store_settings', sa.Column('ai_google_api_key', sa.String(), nullable=True))
    op.add_column('store_settings', sa.Column('ai_openai_api_key', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('store_settings', 'ai_openai_api_key')
    op.drop_column('store_settings', 'ai_google_api_key')
    # ### end Alembic commands ###
