"""Add promotional pricing to marketplace_listings

Revision ID: 10a5479265ec
Revises: d9aa93dc6f66
Create Date: 2026-04-25 06:43:15.228940

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '10a5479265ec'
down_revision: Union[str, Sequence[str], None] = 'd9aa93dc6f66'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('marketplace_listings', sa.Column('original_price', sa.Float(), nullable=True))
    op.add_column('marketplace_listings', sa.Column('discount_percentage', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('marketplace_listings', 'discount_percentage')
    op.drop_column('marketplace_listings', 'original_price')
    # ### end Alembic commands ###
