"""add_expense_user_tracking_fields

Revision ID: 179c66669276
Revises: 180734c2b528
Create Date: 2025-12-29 02:26:29.535693

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '179c66669276'
down_revision: Union[str, Sequence[str], None] = '180734c2b528'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('expenses', sa.Column('paid_by_user_id', sa.Integer(), nullable=True))
    op.add_column('expenses', sa.Column('paid_by_name', sa.String(), nullable=True))
    op.add_column('expenses', sa.Column('is_reimbursed', sa.Boolean(), nullable=True))
    op.add_column('expenses', sa.Column('reimbursed_at', sa.DateTime(timezone=True), nullable=True))
    op.create_foreign_key(None, 'expenses', 'users', ['paid_by_user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'expenses', type_='foreignkey')
    op.drop_column('expenses', 'reimbursed_at')
    op.drop_column('expenses', 'is_reimbursed')
    op.drop_column('expenses', 'paid_by_name')
    op.drop_column('expenses', 'paid_by_user_id')
    # ### end Alembic commands ###
