"""add_expense_tracking_fields

Revision ID: 180734c2b528
Revises: 9683800c79cb
Create Date: 2025-12-29 01:54:45.017202

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '180734c2b528'
down_revision: Union[str, Sequence[str], None] = '9683800c79cb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('expenses', sa.Column('is_custom_category', sa.Boolean(), nullable=True))
    op.add_column('expenses', sa.Column('expense_type', sa.String(), nullable=True))
    op.add_column('expenses', sa.Column('recurrence_interval', sa.String(), nullable=True))
    op.add_column('expenses', sa.Column('reference_number', sa.String(), nullable=True))
    op.add_column('expenses', sa.Column('payment_method', sa.String(), nullable=True))
    op.add_column('expenses', sa.Column('notes', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('expenses', 'notes')
    op.drop_column('expenses', 'payment_method')
    op.drop_column('expenses', 'reference_number')
    op.drop_column('expenses', 'recurrence_interval')
    op.drop_column('expenses', 'expense_type')
    op.drop_column('expenses', 'is_custom_category')
    # ### end Alembic commands ###
