"""add_sync_batch_and_change_log_tables

Revision ID: 1b278953a6ce
Revises: df63319dba4c
Create Date: 2025-12-31 18:29:45.905595

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1b278953a6ce'
down_revision: Union[str, Sequence[str], None] = 'df63319dba4c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sync_batches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('total_changes', sa.Integer(), nullable=True),
    sa.Column('approved_count', sa.Integer(), nullable=True),
    sa.Column('rejected_count', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('reviewed_by_id', sa.Integer(), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['reviewed_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sync_batches_id'), 'sync_batches', ['id'], unique=False)
    op.create_index(op.f('ix_sync_batches_source'), 'sync_batches', ['source'], unique=False)
    op.create_index(op.f('ix_sync_batches_status'), 'sync_batches', ['status'], unique=False)
    op.create_table('entity_change_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=False),
    sa.Column('entity_name', sa.String(length=255), nullable=True),
    sa.Column('field', sa.String(length=100), nullable=False),
    sa.Column('old_value', sa.Text(), nullable=True),
    sa.Column('new_value', sa.Text(), nullable=True),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('source_batch_id', sa.Integer(), nullable=True),
    sa.Column('changed_by_id', sa.Integer(), nullable=False),
    sa.Column('changed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.ForeignKeyConstraint(['changed_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['source_batch_id'], ['sync_batches.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_entity_change_logs_changed_at'), 'entity_change_logs', ['changed_at'], unique=False)
    op.create_index(op.f('ix_entity_change_logs_entity_id'), 'entity_change_logs', ['entity_id'], unique=False)
    op.create_index(op.f('ix_entity_change_logs_entity_type'), 'entity_change_logs', ['entity_type'], unique=False)
    op.create_index(op.f('ix_entity_change_logs_id'), 'entity_change_logs', ['id'], unique=False)
    op.create_index(op.f('ix_entity_change_logs_source'), 'entity_change_logs', ['source'], unique=False)
    op.create_table('pending_sync_changes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('batch_id', sa.Integer(), nullable=False),
    sa.Column('entity', sa.String(length=50), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=False),
    sa.Column('entity_name', sa.String(length=255), nullable=True),
    sa.Column('entity_sku', sa.String(length=100), nullable=True),
    sa.Column('field', sa.String(length=100), nullable=False),
    sa.Column('old_value', sa.Text(), nullable=True),
    sa.Column('new_value', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['batch_id'], ['sync_batches.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pending_sync_changes_entity'), 'pending_sync_changes', ['entity'], unique=False)
    op.create_index(op.f('ix_pending_sync_changes_entity_id'), 'pending_sync_changes', ['entity_id'], unique=False)
    op.create_index(op.f('ix_pending_sync_changes_id'), 'pending_sync_changes', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_pending_sync_changes_id'), table_name='pending_sync_changes')
    op.drop_index(op.f('ix_pending_sync_changes_entity_id'), table_name='pending_sync_changes')
    op.drop_index(op.f('ix_pending_sync_changes_entity'), table_name='pending_sync_changes')
    op.drop_table('pending_sync_changes')
    op.drop_index(op.f('ix_entity_change_logs_source'), table_name='entity_change_logs')
    op.drop_index(op.f('ix_entity_change_logs_id'), table_name='entity_change_logs')
    op.drop_index(op.f('ix_entity_change_logs_entity_type'), table_name='entity_change_logs')
    op.drop_index(op.f('ix_entity_change_logs_entity_id'), table_name='entity_change_logs')
    op.drop_index(op.f('ix_entity_change_logs_changed_at'), table_name='entity_change_logs')
    op.drop_table('entity_change_logs')
    op.drop_index(op.f('ix_sync_batches_status'), table_name='sync_batches')
    op.drop_index(op.f('ix_sync_batches_source'), table_name='sync_batches')
    op.drop_index(op.f('ix_sync_batches_id'), table_name='sync_batches')
    op.drop_table('sync_batches')
    # ### end Alembic commands ###
