"""make_campaign_id_and_connector_user_id_nullable

Revision ID: 3ac6e333067d
Revises: 5f4f5ac38770
Create Date: 2025-12-30 00:14:14.363851

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3ac6e333067d'
down_revision: Union[str, Sequence[str], None] = '5f4f5ac38770'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('campaign_events', 'campaign_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('campaign_events', 'campaign_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
