"""add_variant_id_to_po_item

Revision ID: 409d4dc78229
Revises: e858ffea3084
Create Date: 2026-04-28 06:16:07.569530

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '409d4dc78229'
down_revision: Union[str, Sequence[str], None] = 'e858ffea3084'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('purchase_order_items', sa.Column('variant_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'purchase_order_items', 'product_variants', ['variant_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'purchase_order_items', type_='foreignkey')
    op.drop_column('purchase_order_items', 'variant_id')
    # ### end Alembic commands ###
