"""Add PO models and update Supplier

Revision ID: 425e369a5cfb
Revises: ddad7ea14dc0
Create Date: 2025-12-27 22:09:05.832625

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '425e369a5cfb'
down_revision: Union[str, Sequence[str], None] = 'ddad7ea14dc0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('purchase_orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('supplier_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('total_amount', sa.Float(), nullable=True),
    sa.Column('currency', sa.String(), nullable=True),
    sa.Column('exchange_rate', sa.Float(), nullable=True),
    sa.Column('landed_cost', sa.Float(), nullable=True),
    sa.Column('shipping_cost', sa.Float(), nullable=True),
    sa.Column('tax_amount', sa.Float(), nullable=True),
    sa.Column('other_costs', sa.Float(), nullable=True),
    sa.Column('notes', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_purchase_orders_id'), 'purchase_orders', ['id'], unique=False)
    op.create_table('purchase_order_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('po_id', sa.Integer(), nullable=True),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.Column('quantity_ordered', sa.Float(), nullable=True),
    sa.Column('quantity_received', sa.Float(), nullable=True),
    sa.Column('unit_cost', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['po_id'], ['purchase_orders.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_purchase_order_items_id'), 'purchase_order_items', ['id'], unique=False)
    op.create_table('supplier_invoices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('po_id', sa.Integer(), nullable=True),
    sa.Column('invoice_number', sa.String(), nullable=True),
    sa.Column('invoice_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('file_path', sa.String(), nullable=True),
    sa.Column('parsed_data', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['po_id'], ['purchase_orders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_supplier_invoices_id'), 'supplier_invoices', ['id'], unique=False)
    op.create_index(op.f('ix_supplier_invoices_invoice_number'), 'supplier_invoices', ['invoice_number'], unique=False)
    op.add_column('products', sa.Column('supplier_sku', sa.String(), nullable=True))
    op.create_index(op.f('ix_products_supplier_sku'), 'products', ['supplier_sku'], unique=False)
    op.add_column('suppliers', sa.Column('address_street', sa.String(), nullable=True))
    op.add_column('suppliers', sa.Column('address_city', sa.String(), nullable=True))
    op.add_column('suppliers', sa.Column('address_state', sa.String(), nullable=True))
    op.add_column('suppliers', sa.Column('address_zip', sa.String(), nullable=True))
    op.add_column('suppliers', sa.Column('address_country', sa.String(), nullable=True))
    op.add_column('suppliers', sa.Column('tax_id', sa.String(), nullable=True))
    op.add_column('suppliers', sa.Column('payment_terms', sa.String(), nullable=True))
    op.add_column('suppliers', sa.Column('currency', sa.String(), nullable=True))
    op.add_column('suppliers', sa.Column('website', sa.String(), nullable=True))
    op.add_column('suppliers', sa.Column('internal_notes', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('suppliers', 'internal_notes')
    op.drop_column('suppliers', 'website')
    op.drop_column('suppliers', 'currency')
    op.drop_column('suppliers', 'payment_terms')
    op.drop_column('suppliers', 'tax_id')
    op.drop_column('suppliers', 'address_country')
    op.drop_column('suppliers', 'address_zip')
    op.drop_column('suppliers', 'address_state')
    op.drop_column('suppliers', 'address_city')
    op.drop_column('suppliers', 'address_street')
    op.drop_index(op.f('ix_products_supplier_sku'), table_name='products')
    op.drop_column('products', 'supplier_sku')
    op.drop_index(op.f('ix_supplier_invoices_invoice_number'), table_name='supplier_invoices')
    op.drop_index(op.f('ix_supplier_invoices_id'), table_name='supplier_invoices')
    op.drop_table('supplier_invoices')
    op.drop_index(op.f('ix_purchase_order_items_id'), table_name='purchase_order_items')
    op.drop_table('purchase_order_items')
    op.drop_index(op.f('ix_purchase_orders_id'), table_name='purchase_orders')
    op.drop_table('purchase_orders')
    # ### end Alembic commands ###
