"""add_average_cost_to_product

Revision ID: 4761955010d3
Revises: 0008_add_supplier_products
Create Date: 2025-12-28 03:42:48.493281

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4761955010d3'
down_revision: Union[str, Sequence[str], None] = '0008_add_supplier_products'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('average_cost', sa.Float(), nullable=True))
    op.drop_constraint(op.f('uq_supplier_product'), 'supplier_products', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('uq_supplier_product'), 'supplier_products', ['product_id', 'supplier_id'], postgresql_nulls_not_distinct=False)
    op.drop_column('products', 'average_cost')
    # ### end Alembic commands ###
