"""add_smtp_password_encrypted_to_store_settings

Revision ID: 5f4f5ac38770
Revises: c2c5e14e33a5
Create Date: 2025-12-29 23:52:40.930255

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5f4f5ac38770'
down_revision: Union[str, Sequence[str], None] = 'c2c5e14e33a5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('store_settings', sa.Column('smtp_password_encrypted', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('store_settings', 'smtp_password_encrypted')
    # ### end Alembic commands ###
