"""Refine marketplace models and add credentials

Revision ID: 79262359b5a8
Revises: 01202be541dc
Create Date: 2025-12-27 22:27:27.240657

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '79262359b5a8'
down_revision: Union[str, Sequence[str], None] = '01202be541dc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('marketplace_credentials', sa.Column('token_type', sa.String(), nullable=True))
    op.add_column('marketplace_credentials', sa.Column('scopes', sa.String(), nullable=True))
    op.add_column('marketplace_credentials', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.add_column('marketplace_credentials', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    op.alter_column('marketplace_credentials', 'expires_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('marketplace_credentials', 'expires_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.drop_column('marketplace_credentials', 'updated_at')
    op.drop_column('marketplace_credentials', 'created_at')
    op.drop_column('marketplace_credentials', 'scopes')
    op.drop_column('marketplace_credentials', 'token_type')
    # ### end Alembic commands ###
