"""Add low stock quantity settings

Revision ID: 7960771df521
Revises: da0d3ac2bbe6
Create Date: 2025-12-29 16:45:26.410449

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7960771df521'
down_revision: Union[str, Sequence[str], None] = 'da0d3ac2bbe6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product_inventory_settings', sa.Column('low_stock_quantity_threshold', sa.Integer(), nullable=True))
    op.add_column('store_settings', sa.Column('low_stock_quantity_default', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('store_settings', 'low_stock_quantity_default')
    op.drop_column('product_inventory_settings', 'low_stock_quantity_threshold')
    # ### end Alembic commands ###
