"""add_store_domain_columns

Revision ID: 9d9a9a987ee4
Revises: d3d1217bde50
Create Date: 2026-01-03 08:13:11.401992

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9d9a9a987ee4'
down_revision: Union[str, Sequence[str], None] = 'd3d1217bde50'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('store_settings', sa.Column('store_domain', sa.String(), nullable=True))
    op.add_column('store_settings', sa.Column('store_name', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('store_settings', 'store_name')
    op.drop_column('store_settings', 'store_domain')
    # ### end Alembic commands ###
