"""Add Multi-Provider AI Settings

Revision ID: d3d1217bde50
Revises: ddf91a36b702
Create Date: 2026-01-03 07:14:06.959093

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd3d1217bde50'
down_revision: Union[str, Sequence[str], None] = 'ddf91a36b702'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('store_settings', sa.Column('ai_enabled', sa.Integer(), nullable=True))
    op.add_column('store_settings', sa.Column('ai_provider', sa.String(), nullable=True))
    op.add_column('store_settings', sa.Column('ai_model', sa.String(), nullable=True))
    op.add_column('store_settings', sa.Column('ai_anthropic_api_key', sa.String(), nullable=True))
    op.add_column('store_settings', sa.Column('ai_qwen_api_key', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('store_settings', 'ai_qwen_api_key')
    op.drop_column('store_settings', 'ai_anthropic_api_key')
    op.drop_column('store_settings', 'ai_model')
    op.drop_column('store_settings', 'ai_provider')
    op.drop_column('store_settings', 'ai_enabled')
    # ### end Alembic commands ###
