"""Inventory settings

Revision ID: da0d3ac2bbe6
Revises: dc46217fe614
Create Date: 2025-12-29 16:36:24.215262

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'da0d3ac2bbe6'
down_revision: Union[str, Sequence[str], None] = 'dc46217fe614'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('store_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('settings', sa.JSON(), nullable=True),
    sa.Column('low_inventory_days_default', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_store_settings_id'), 'store_settings', ['id'], unique=False)
    op.create_table('product_inventory_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('low_inventory_days_threshold', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('product_id')
    )
    op.create_index(op.f('ix_product_inventory_settings_id'), 'product_inventory_settings', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_product_inventory_settings_id'), table_name='product_inventory_settings')
    op.drop_table('product_inventory_settings')
    op.drop_index(op.f('ix_store_settings_id'), table_name='store_settings')
    op.drop_table('store_settings')
    # ### end Alembic commands ###
