"""add_po_dates

Revision ID: dc46217fe614
Revises: f7b2b422a1bf
Create Date: 2025-12-29 16:00:15.955982

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dc46217fe614'
down_revision: Union[str, Sequence[str], None] = 'f7b2b422a1bf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('purchase_orders', sa.Column('ordered_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('purchase_orders', sa.Column('received_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('purchase_orders', 'received_at')
    op.drop_column('purchase_orders', 'ordered_at')
    # ### end Alembic commands ###
