"""Add barcode value columns

Revision ID: ddf91a36b702
Revises: 028534179c86
Create Date: 2026-01-03 06:32:37.374116

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ddf91a36b702'
down_revision: Union[str, Sequence[str], None] = '028534179c86'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('barcode_value', sa.String(), nullable=True))
    op.add_column('products', sa.Column('qrcode_value', sa.String(), nullable=True))
    op.create_index(op.f('ix_products_barcode_value'), 'products', ['barcode_value'], unique=False)
    op.create_index(op.f('ix_products_qrcode_value'), 'products', ['qrcode_value'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_products_qrcode_value'), table_name='products')
    op.drop_index(op.f('ix_products_barcode_value'), table_name='products')
    op.drop_column('products', 'qrcode_value')
    op.drop_column('products', 'barcode_value')
    # ### end Alembic commands ###
