"""Add supplier_product_name to supplier_products

Revision ID: e858ffea3084
Revises: 10a5479265ec
Create Date: 2026-04-28 05:28:43.934767

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e858ffea3084'
down_revision: Union[str, Sequence[str], None] = '10a5479265ec'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('supplier_products', sa.Column('supplier_product_name', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('supplier_products', 'supplier_product_name')
    # ### end Alembic commands ###
