"""Add new fields to Product model

Revision ID: f4263badb1f8
Revises: 559065695c93
Create Date: 2025-10-11 17:36:20.642859

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f4263badb1f8'
down_revision: Union[str, Sequence[str], None] = '559065695c93'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('manufacturer', sa.String(), nullable=True))
    op.add_column('products', sa.Column('brand', sa.String(), nullable=True))
    op.add_column('products', sa.Column('category', sa.String(), nullable=True))
    op.add_column('products', sa.Column('width', sa.Float(), nullable=True))
    op.add_column('products', sa.Column('height', sa.Float(), nullable=True))
    op.add_column('products', sa.Column('depth', sa.Float(), nullable=True))
    op.add_column('products', sa.Column('weight', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'weight')
    op.drop_column('products', 'depth')
    op.drop_column('products', 'height')
    op.drop_column('products', 'width')
    op.drop_column('products', 'category')
    op.drop_column('products', 'brand')
    op.drop_column('products', 'manufacturer')
    # ### end Alembic commands ###
