"""add_force_password_change_to_user

Revision ID: f49850b583ab
Revises: 0006_add_avatar_to_user
Create Date: 2025-11-30 07:55:15.573726

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f49850b583ab'
down_revision: Union[str, Sequence[str], None] = '0006_add_avatar_to_user'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product_templates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('brand', sa.String(), nullable=True),
    sa.Column('default_resale_price', sa.Float(), nullable=True),
    sa.Column('cost_price', sa.Float(), nullable=True),
    sa.Column('manufacturer', sa.String(), nullable=True),
    sa.Column('width', sa.Float(), nullable=True),
    sa.Column('height', sa.Float(), nullable=True),
    sa.Column('depth', sa.Float(), nullable=True),
    sa.Column('weight', sa.Float(), nullable=True),
    sa.Column('properties', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_product_templates_id'), 'product_templates', ['id'], unique=False)
    op.create_table('custom_field_templates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('template_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('type', sa.String(), nullable=True),
    sa.Column('default_value', sa.String(), nullable=True),
    sa.Column('required', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['template_id'], ['product_templates.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_custom_field_templates_id'), 'custom_field_templates', ['id'], unique=False)
    op.alter_column('inventory_adjustments', 'timestamp',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('inventory_adjustments', 'created_by',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_index(op.f('ix_inventory_adjustments_product_id'), table_name='inventory_adjustments')
    op.drop_index(op.f('ix_password_reset_tokens_user_id'), table_name='password_reset_tokens')
    op.drop_constraint(op.f('product_custom_fields_product_id_fkey'), 'product_custom_fields', type_='foreignkey')
    op.create_foreign_key(None, 'product_custom_fields', 'products', ['product_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('product_images_product_id_fkey'), 'product_images', type_='foreignkey')
    op.create_foreign_key(None, 'product_images', 'products', ['product_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_product_variants_product_id'), table_name='product_variants')
    op.alter_column('user_audit_logs', 'action',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_index(op.f('ix_user_audit_logs_action_performed_by'), table_name='user_audit_logs')
    op.drop_index(op.f('ix_user_audit_logs_user_id'), table_name='user_audit_logs')
    op.add_column('users', sa.Column('force_password_change', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'force_password_change')
    op.create_index(op.f('ix_user_audit_logs_user_id'), 'user_audit_logs', ['user_id'], unique=False)
    op.create_index(op.f('ix_user_audit_logs_action_performed_by'), 'user_audit_logs', ['action_performed_by'], unique=False)
    op.alter_column('user_audit_logs', 'action',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.create_index(op.f('ix_product_variants_product_id'), 'product_variants', ['product_id'], unique=False)
    op.drop_constraint(None, 'product_images', type_='foreignkey')
    op.create_foreign_key(op.f('product_images_product_id_fkey'), 'product_images', 'products', ['product_id'], ['id'])
    op.drop_constraint(None, 'product_custom_fields', type_='foreignkey')
    op.create_foreign_key(op.f('product_custom_fields_product_id_fkey'), 'product_custom_fields', 'products', ['product_id'], ['id'])
    op.create_index(op.f('ix_password_reset_tokens_user_id'), 'password_reset_tokens', ['user_id'], unique=False)
    op.create_index(op.f('ix_inventory_adjustments_product_id'), 'inventory_adjustments', ['product_id'], unique=False)
    op.alter_column('inventory_adjustments', 'created_by',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('inventory_adjustments', 'timestamp',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.drop_index(op.f('ix_custom_field_templates_id'), table_name='custom_field_templates')
    op.drop_table('custom_field_templates')
    op.drop_index(op.f('ix_product_templates_id'), table_name='product_templates')
    op.drop_table('product_templates')
    # ### end Alembic commands ###
