"""add_po_payment_fields

Revision ID: f7b2b422a1bf
Revises: 179c66669276
Create Date: 2025-12-29 05:05:08.877511

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f7b2b422a1bf'
down_revision: Union[str, Sequence[str], None] = '179c66669276'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('purchase_orders', sa.Column('payment_status', sa.String(), nullable=True))
    op.add_column('purchase_orders', sa.Column('payment_method', sa.String(), nullable=True))
    op.add_column('purchase_orders', sa.Column('custom_payer_name', sa.String(), nullable=True))
    op.add_column('purchase_orders', sa.Column('paid_by_user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'purchase_orders', 'users', ['paid_by_user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'purchase_orders', type_='foreignkey')
    op.drop_column('purchase_orders', 'paid_by_user_id')
    op.drop_column('purchase_orders', 'custom_payer_name')
    op.drop_column('purchase_orders', 'payment_method')
    op.drop_column('purchase_orders', 'payment_status')
    # ### end Alembic commands ###
