"""add_product_image_order

Revision ID: ff6991430d3a
Revises: 92147800281d
Create Date: 2026-01-10 20:41:20.471344

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ff6991430d3a'
down_revision: Union[str, Sequence[str], None] = '92147800281d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product_images', sa.Column('order', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_product_images_order'), 'product_images', ['order'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_product_images_order'), table_name='product_images')
    op.drop_column('product_images', 'order')
    # ### end Alembic commands ###
