name: Frontend CI

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
    paths:
      - 'frontend/**'
  pull_request:
    branches: [ "main" ]
    paths:
      - 'frontend/**'

jobs:
  frontend-test:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true
    defaults:
      run:
        working-directory: ./frontend

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'pnpm'
          cache-dependency-path: frontend/pnpm-lock.yaml

      - name: Install Dependencies
        run: pnpm install

      - name: Run Tests
        run: pnpm test